config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  root 'users#index'

  resources :friendship_requests, except: [:edit, :update] do
    patch :accept, on: :member
    patch :decline, on: :member
    collection do
      get :outgoing
    end
  end

  get 'friends' => 'friends#index'
  patch 'friends/:id/relieve' => 'friends#relieve', as: :relieve_friend

end

app/models/friendship_request.rb
class FriendshipRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  enum status: [:pending, :accepted, :declined, :relieved]
  validates_uniqueness_of :user_id, scope: :friend_id,
            message: 'Already have requested friendship of this user'
  validate :friend_id, :has_incoming_request

  def has_incoming_request
    if self.class.exists?(friend_id: user_id, user_id: friend_id)
      errors.add(:friend_id, :already_have_request_from_that_user)
    end
  end
  def relieve!
    self.destroy
  end

end

app/controllers/friendship_requests_controller.rb
class FriendshipRequestsController < ApplicationController
  before_action :set_friendship_request, only: [:show, :edit, :update, :destroy, :accept, :decline]
  before_action :set_friend, only: [:new, :create]
  before_action :authenticate_user!

  # GET /friendship_requests
  # GET /friendship_requests.json
  def index
    @friendship_requests = FriendshipRequest.where(friend: current_user)
  end

  # GET /friendship_requests/outgoing
  # GET /friendship_requests/outgoing.json
  def outgoing
    @friendship_requests = FriendshipRequest.where(user: current_user)
  end

  # GET /friendship_requests/1
  # GET /friendship_requests/1.json
  def show
  end

  # GET /friendship_requests/new
  def new
    @friendship_request = FriendshipRequest.new(user: current_user, friend: @friend)
  end

  # GET /friendship_requests/1/edit
  def edit
  end

  # POST /friendship_requests
  # POST /friendship_requests.json
  def create
    @friendship_request = FriendshipRequest.new(friendship_request_params)
    @friendship_request.user = current_user
    respond_to do |format|
      if @friendship_request.save
        format.html { redirect_to @friendship_request, notice: 'Friendship request was successfully created.' }
        format.json { render :show, status: :created, location: @friendship_request }
      else
        format.html { render :new }
        format.json { render json: @friendship_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendship_requests/1
  # PATCH/PUT /friendship_requests/1.json
  def update
    respond_to do |format|
      if @friendship_request.update(friendship_request_params)
        format.html { redirect_to @friendship_request, notice: 'Friendship request was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship_request }
      else
        format.html { render :edit }
        format.json { render json: @friendship_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /friendship_requests/1/accept
  def accept
    @friendship_request.update_attribute(:status, :accepted)
    respond_to do |format|
      format.html { redirect_to friendship_requests_url, notice: 'Friendship request has been accepted.' }
      format.json { render :show, status: :ok, location: @friendship_request }
    end
  end

  # PATCH /friendship_requests/1/decline
  def decline
    @friendship_request.update_attribute(:status, :declined)
    respond_to do |format|
      format.html { redirect_to friendship_requests_url, notice: 'Friendship request has been declined.' }
      format.json { render :show, status: :ok, location: @friendship_request }
    end
  end

  # DELETE /friendship_requests/1
  # DELETE /friendship_requests/1.json
  def destroy
    @friendship_request = FriendshipRequest
                              .where(user_id: current_user.id)
                              .find(params[:id])
    @friendship_request.destroy
    respond_to do |format|
      format.html { redirect_to friendship_requests_url, notice: 'Friendship request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship_request
      @friendship_request = FriendshipRequest.find(params[:id])
    end

    def set_friend
      @friend = User.find(params[:friend_id]) if params.include? :friend_id
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_request_params
      params.require(:friendship_request).permit(:user_id, :friend_id)
    end
end

app/helpers/friendship_requests_helper.rb
module FriendshipRequestsHelper
end

app/views/friendship_requests/_form.html.slim
= bootstrap_form_for @friendship_request do |f|
  = f.alert_message t(:fix_errors_below)
  .field
    = f.collection_select :friend_id, User.all, :id, :email
  .actions = f.submit

app/views/friendship_requests/index.html.slim
h1 Listing Friendship requests

h2 Pending
table.table
  - @friendship_requests.pending.each do |friendship_request|
    tr
      td = friendship_request.user.email
      td = friendship_request.status
      td
        = link_to 'Accept', accept_friendship_request_path(friendship_request), method: :patch
        | |
        = link_to 'Decline', decline_friendship_request_path(friendship_request), method: :patch

h2 Declined
table.table
  - @friendship_requests.declined.each do |friendship_request|
    tr
      td = friendship_request.user.email
      td = friendship_request.status
      td
        = link_to 'Accept', accept_friendship_request_path(friendship_request), method: :patch

h2 Accepted
table.table
  - @friendship_requests.accepted.each do |friendship_request|
    tr
      td = friendship_request.user.email
      td = friendship_request.status
      td
        = link_to 'Decline', decline_friendship_request_path(friendship_request), method: :patch

br
= link_to 'New Friendship request', new_friendship_request_path

app/views/friendship_requests/new.html.slim
h1 New Friendship request

== render 'form'

= link_to 'Back', friendship_requests_path

app/views/friendship_requests/outgoing.html.slim
h1 Listing Friendship requests

h3 Pending
table.table
  - @friendship_requests.pending.each do |friendship_request|
    tr
      td = friendship_request.friend.email
      td
        = link_to 'Delete', friendship_request, method: :delete

h3 Declined
table.table
  - @friendship_requests.declined.each do |friendship_request|
    tr
      td = friendship_request.friend.email
      td = friendship_request.status
      td
        = link_to 'Accept', accept_friendship_request_path(friendship_request), method: :patch

h3 Accepted
table.table
  - @friendship_requests.accepted.each do |friendship_request|
    tr
      td = friendship_request.friend.email
      td = friendship_request.status
      td
        = link_to 'Decline', decline_friendship_request_path(friendship_request), method: :patch

br

= link_to 'New Friendship request', new_friendship_request_path

app/views/friendship_requests/show.html.slim
p
  strong Friend:
  = @friendship_request.friend.email

= link_to 'Back', friendship_requests_path