config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  root 'users#index'

  resources :friendship_requests, except: [:edit, :update] do
    patch :accept, on: :member
    patch :decline, on: :member
    collection do
      get :outgoing
    end
  end

  get 'friends' => 'friends#index'
  patch 'friends/:id/relieve' => 'friends#relieve', as: :relieve_friend

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendship_requests
  has_many :accepted_friendship_requests,
           -> { where status: FriendshipRequest.statuses[:accepted] },
           class_name: 'FriendshipRequest'
  has_many :friends, through: :accepted_friendship_requests, source: :user

  has_many :inverse_friendship_requests, class_name: 'FriendshipRequest', foreign_key: :friend_id
  has_many :accepted_inverse_friendship_requests,
           -> { where status: FriendshipRequest.statuses[:accepted] },
           class_name: 'FriendshipRequest', foreign_key: :friend_id
  has_many :inverse_friends, through: :accepted_inverse_friendship_requests, source: :user

  def self.regular(user_id)
    eager_load(:friendship_requests, :inverse_friendship_requests)
      .where.not(id: user_id)
  end

  def relieve_friend!(user)
    friendship_requests.where(friend_id: user.id).each do |request|
      request.relieve!
    end
    inverse_friendship_requests.where(user_id: user.id).each do |request|
      request.relieve!
    end
  end

  def friendship_request_with(user)
    friendship_requests.where(user_id: self.id, friend_id: user.id).first ||
        inverse_friendship_requests.where(friend_id: self.id, user_id: user.id).first
  end

  def is_a_friend_of?(user)
    accepted_friendship_requests.where(friend_id: user.id).any? ||
        accepted_inverse_friendship_requests.where(user_id: user.id).any?
  end

  def has_friendship_request_from?(user)
    inverse_friendship_requests.where(user_id: user.id).any?
  end

  def has_friendship_request_to?(user)
    friendship_requests.where(friend_id: user.id).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.regular(current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/users/_friendship_status.html.slim
- if current_user.is_a_friend_of?(user)
  .name= t(:friends)
  = link_to t(:relieve_friend), relieve_friend_path(user), method: :patch
- elsif current_user.has_friendship_request_from?(user)
  = link_to 'Add to friends', new_friendship_request_path(friend_id: user.id)
- elsif current_user.has_friendship_request_to?(user)
  = link_to 'Revoke', friendship_request_path(current_user.friendship_request_with user), method: :delete
- else
  = link_to 'Add to friends', new_friendship_request_path(friend_id: user.id)

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table.table
  thead
    tr
      th Email
      th Status
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = render 'users/friendship_status', user: user
        td = link_to 'Show', user
br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path