config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  root 'users#index'

  resources :friendship_requests, except: [:edit, :update] do
    patch :accept, on: :member
    patch :decline, on: :member
    collection do
      get :outgoing
    end
  end

  get 'friends' => 'friends#index'
  patch 'friends/:id/relieve' => 'friends#relieve', as: :relieve_friend

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Friends Swamp', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
/ add navigation links to this file
li= link_to 'Users', users_path
li= link_to 'Friends', friends_path
li= link_to 'Requests (Incoming)', friendship_requests_path
li= link_to 'Requests (Outgoing)', outgoing_friendship_requests_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Friend Swamp'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Friend Swamp'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield